services:

 nextcloud:
    image: nextcloud # The image that will be used. The official nextcloud docker
    container_name: nextcloud # Just the name of the container. Help you identify it
    restart: unless-stopped # If something happens like the container crashes then we want the container to start up again
    networks: # Link all the containers through the network "cloud"
      - cloud
    depends_on: # Wait for the database and redis containers before starting nextcloud
      - nextclouddb 
      - redis
    ports: # If you have multiple web service on your server you need to change the port. I am directing nextcloud from port 80 to port 8081
      - 4545:80
    volumes: # These are important. This will map a file directory inside the container to a directory on your actual computer
      - ./html:/var/www/html # Map the /var/www/html directory in the container to the html folder in the same folder as the docker-compose.yml
      - ./custom_apps:/var/www/html/custom_apps # These volumes allow us to easily interact with the files in the container
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - PUID=1000 # The user ids. Most likely both should be 1000. Incorrectly setting these will led to file permission issues
      - PGID=1000 # Set these to whatever your user is.
      - TZ=America/Los_Angeles # Set this to your timezone
      - MYSQL_DATABASE=nextcloud # This is the database information we will set up in the next section
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis # The redis container to use

 nextclouddb:
    image: mariadb # offical mariadb image
    container_name: nextcloud-db 
    restart: unless-stopped 
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW # I honestly cant remember. If you know why let me know.
    networks: 
      - cloud
    volumes:
      - ./nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000 # Should be the same as the other containers
      - PGID=1000
      - TZ=America/Los_Angeles
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=dbpassword # Same information that was entered in the nextcloud portion
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

 collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    networks: 
      - cloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles # Should be the same as the others 
      - password=password 
      - username=nextcloud
      - domain=example.com # domain your nextcloud is on
      - extra_params=--o:ssl.enable=true # Use if have ssl. You should.
    ports:
      - 9980:9980

 redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data  
    networks: 
      - cloud

networks:
  cloud:
    name: cloud
    driver: bridge
